### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by ktfth** [lisajamhoury/simple-peer-wrapper#2]
Can you explain how to open two differente instances of the same example? Because them are not working for my case.

Thank you

**Comment by lisajamhoury** [comment]
Are you running into any specific errors? If so, please copy and past here or send me a screen shot. 

Have you read this article? Maybe it helps? https://javascript.plainenglish.io/building-a-signaling-server-for-simple-peer-f92d754edc85

If not I can make you a video of how to run the examples sometime this or next week. Lmk.

**Comment by ktfth** [comment]
I'm gonna check this out, thank you

**Comment by ktfth** [comment]
The example work

**Comment by lisajamhoury** [comment]
Excellent!
