### ISSUE TITLE
connection event doesn't propagate

### ISSUE THREAD

**Issue by brianorwhatever** [lisajamhoury/simple-peer-wrapper#4]
As you can see here the 'connect' event isn't passed on so this makes it impossible to do anything once the connection has been established
https://github.com/lisajamhoury/simple-peer-wrapper/blob/3b17a45f82b8a9334464d67136b397026b42895e/src/simple-peer-client-wrapper.js#L161

**Comment by brianorwhatever** [comment]
awesome, thank you @lisajamhoury

**Comment by lisajamhoury** [comment]
no problem. thanks for pointing it out. lmk if you have other issues. example of usage here: 

https://github.com/lisajamhoury/simple-peer-wrapper/blob/4ebdf88dbb3074325e75c802379a2a3df1edbe4e/examples/ex1_mouse/sketch.js#L50

fixed in v 0.0.4
